# Generated by Django 5.1.1 on 2024-09-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactscompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactscompany',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
